# Generated by Django 5.1.3 on 2024-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
